services:
  - type: web
    name: api-integracao
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: BETTERSTACK_URL
        sync: false
      - key: BETTERSTACK_TOKEN
        sync: false
    buildCommand: echo "Build completed"
    startCommand: npm start 